investigates i3-troubleshoot-ci

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -24,6 +24,10 @@ on:
         required: false
         type: string
         default: "gem install semaphore_test_boosters && rspec_booster --job $CI_NODE_INDEX/$CI_NODE_TOTAL"
+      setup_db_cmd:
+        required: false
+        type: string
+        default: "RAILS_ENV=test bundle exec rake db:create db:schema:load db:migrate"
       worker:
         required: false
         type: boolean
@@ -51,6 +55,10 @@ on:
         required: false
         type: string
         default: "gem install semaphore_test_boosters && rspec_booster --job $CI_NODE_INDEX/$CI_NODE_TOTAL"
+      setup_db_cmd:
+        required: false
+        type: string
+        default: "RAILS_ENV=test bundle exec rake db:create db:schema:load db:migrate"
       worker:
         required: false
         type: boolean
@@ -63,21 +71,20 @@ jobs:
     runs-on: self-hosted
     strategy:
       fail-fast: true
-      # matrix:
-      #   # Set N number of parallel jobs you want to run tests on.
-      #   # Use higher number if you have slow tests to split them on more parallel jobs.
-      #   # Remember to update ci_node_index below to 0..N-1
-      #   ci_node_total: [1]
-      #   # set N-1 indexes for parallel jobs
-      #   # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
-      #   ci_node_index: [0, 1, 2]
+      matrix:
+        # # Set N number of parallel jobs you want to run tests on.
+        # # Use higher number if you have slow tests to split them on more parallel jobs.
+        # # Remember to update ci_node_index below to 0..N-1
+        # ci_node_total: [3]
+        # # set N-1 indexes for parallel jobs
+        # # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
+        # ci_node_index: [0, 1, 2]
     env:
       ALLOW_ANONYMOUS_LOGIN: "yes"
       CONFDIR: ${{ inputs.confdir }}
       DB_CLEANER_ALLOW_REMOTE_DB_URL: "true"
       TB_RSPEC_FORMATTER: progress
       TB_RSPEC_OPTIONS: --format RspecJunitFormatter --out rspec.xml
-      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     steps:
       - id: setup
         name: Setup
@@ -85,8 +92,7 @@ jobs:
         with:
           tag: ${{ inputs.tag }}
           image_name: ${{ inputs.image_name }}
-      - name: Checkout code
-        uses: actions/checkout@v3
+          token: ${{ secrets.CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v2
         with:
@@ -127,32 +133,30 @@ jobs:
       - name: Setup tmate session
         uses: mxschmitt/action-tmate@v3
         if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           limit-access-to-actor: true
       - name: Setup db
         run: >-
           cd ${{ inputs.subdir }};
           docker-compose exec -T web sh -c
-          "mysql -p\$MYSQL_PASSWORD -uroot -h \$MYSQL_HOST -e \"create database \$TEST_DB;\";
-          mysql -p\$MYSQL_PASSWORD -uroot -h \$MYSQL_HOST -e \"use \$TEST_DB; GRANT ALL PRIVILEGES ON *.* TO '\$MYSQL_USER'@'%'; FLUSH PRIVILEGES;\";
-          RAILS_ENV=test bundle exec rake db:schema:load db:migrate"
+          "${{ inputs.setup_db_cmd }}"
       - name: Run Specs
+        id: run-specs
         env:
           # Specifies how many jobs you would like to run in parallel,
           # used for partitioning
           CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
           # Use the index from matrix as an environment variable
           CI_NODE_INDEX: ${{ matrix.ci_node_index }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        # continue-on-error: true
+        continue-on-error: true
         run: >-
           cd ${{ inputs.subdir }};
           docker-compose exec -T web sh -c
           "${{ inputs.rspec_cmd }}"
-      # - name: Publish Test Report
-      #   uses: mikepenz/action-junit-report@v3
-      #   if: always() # always run even if the previous step fails
-      #   with:
-      #     report_paths: 'rspec*.xml'
+      - name: Fail job if spec failure
+        run: if [[ ${{ steps.run-specs.outcome }} == "failure" ]]; then exit 1; else exit 0; fi
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: always() # always run even if the previous step fails
+        with:
+          report_paths: 'rspec*.xml'
